-- REINITIALIZE ALL TABLES

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Account')
BEGIN
	TRUNCATE TABLE Account
	DBCC CHECKIDENT ('Account', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'AccountType')
BEGIN
	TRUNCATE TABLE AccountType
	DBCC CHECKIDENT ('AccountType', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'BankTransaction')
BEGIN
	TRUNCATE TABLE BankTransaction
	DBCC CHECKIDENT ('BankTransaction', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'InvTransaction')
BEGIN
	TRUNCATE TABLE InvTransaction
	DBCC CHECKIDENT ('InvTransaction', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Budget')
BEGIN
	TRUNCATE TABLE Budget
	DBCC CHECKIDENT ('Budget', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Category')
BEGIN
	TRUNCATE TABLE Category
	DBCC CHECKIDENT ('Category', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Subcategory')
BEGIN
	TRUNCATE TABLE Subcategory
	DBCC CHECKIDENT ('Subcategory', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Class')
BEGIN
	TRUNCATE TABLE Class
	DBCC CHECKIDENT ('Class', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Subclass')
BEGIN
	TRUNCATE TABLE Subclass
	DBCC CHECKIDENT ('Subclass', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Institution')
BEGIN
	TRUNCATE TABLE Institution
	DBCC CHECKIDENT ('Institution', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Payee')
BEGIN
	TRUNCATE TABLE Payee
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Investment')
BEGIN
	TRUNCATE TABLE Investment
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'InvestmentAction')
BEGIN
	TRUNCATE TABLE InvestmentAction
	DBCC CHECKIDENT ('InvestmentAction', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Scheduled')
BEGIN
	TRUNCATE TABLE Scheduled
	DBCC CHECKIDENT ('Scheduled', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'ScheduledRule')
BEGIN
	TRUNCATE TABLE ScheduledRule
	DBCC CHECKIDENT ('ScheduledRule', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'ScheduledType')
BEGIN
	TRUNCATE TABLE ScheduledType
	DBCC CHECKIDENT ('ScheduledType', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Subtransaction')
BEGIN
	TRUNCATE TABLE Subtransaction
	DBCC CHECKIDENT ('Subtransaction', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'ScheduleTransaction')
BEGIN
	TRUNCATE TABLE ScheduleTransaction
	DBCC CHECKIDENT ('ScheduleTransaction', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'ScheduleSubtransaction')
BEGIN
	TRUNCATE TABLE ScheduleSubtransaction
	DBCC CHECKIDENT ('ScheduleSubtransaction', RESEED, 1)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'ScheduleRule')
BEGIN
	TRUNCATE TABLE ScheduleRule
	DBCC CHECKIDENT ('ScheduleRule', RESEED, 1)
END
GO
